# http://module-build.sourceforge.net/META-spec.html
#
name:         Text::Phonetic::Soundex::Length
version:      1.0
version_from: Length.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
